### ISSUE TITLE
Bridge methods undefined

### ISSUE THREAD

**Issue by wferreira** [hybridgroup/cylon-hue#3]
Hi,

getting the following issue with Cylon 0.22.0 and cylon-hue 0.4.0.
Seems to be related to the update in 0.21.0 : 
"in Adaptor subclasses, instead of referencing this.connection, just reference this".

TypeError: Object #<Adaptor> has no method 'getFullState'
    at Bridge.getFullState (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon-hue/lib/bridge.js:122:19)
    at Driver.<anonymous> (/Users/will/dev/projets/Perso/LeapToHue/app.js:22:17)
    at Driver.emit (events.js:95:17)
    at Adaptor.<anonymous> (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon/lib/basestar.js:54:22)
    at Adaptor.emit (events.js:95:17)
    at Leap.loop.hand (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon-leapmotion/lib/adaptor.js:92:7)
    at emit (events.js:95:17)
    at Controller.emitHandEvents (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon-leapmotion/node_modules/leapjs/lib/controller.js:259:10)
    at Controller.processFinishedFrame (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon-leapmotion/node_modules/leapjs/lib/controller.js:248:8)
    at null.<anonymous> (/Users/will/dev/projets/Perso/LeapToHue/node_modules/cylon-leapmotion/node_modules/leapjs/lib/controller.js:301:16)

Thanks

**Comment by wferreira** [comment]
issue was related to an other adaptor (cylon-leapmotion)
